//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesStore.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductOrder = new HashSet<ProductOrder>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ManufacturerID { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> Discount { get; set; }
        public int Quantity { get; set; }
        public string Image { get; set; }

        public string NameView
        {
            get
            {
                return "Наименование: " + this.Name;
            }
        }
        public string DescriptionView
        {
            get
            {
                return "Описание: " + this.Description;
            }
        }
        public string ManufacturerView
        {
            get
            {
                return "Производитель: " + Manufacturer.Name;
            }
        }
        public string PriceView
        {
            get
            {
                return "Стоимость: " + this.Price.ToString() + " Руб";
            }
        }
        public string DiscountView
        {
            get
            {
                if (this.Discount != null)
                {
                    return "Скидка: " + this.Discount.ToString() + " %";
                }
                else
                {
                    return string.Empty;
                }
            }
        }
        public string QuantityView
        {
            get
            {
                return "Количество: " + this.Quantity + " шт";
            }
        }

        public string ImageView
        {
            get
            {
                return "/Resources/" + this.Image + ".png";
            }
        }
    
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOrder> ProductOrder { get; set; }
    }
}
